accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('reviews/', include('reviews.urls')),
]

reviews/urls.py
from django.urls import path
from . import views

app_name = 'reviews'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/comments/', views.comments, name='comments'),
    path('<int:review_pk>/comments/<int:comment_pk>/delete/', views.comments_del, name='comments_del'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    pass

reviews/models.py
from django.db import models
from django.conf import settings

# Create your models here.

class Review(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=80)
    content = models.TextField()
    movie_name = models.CharField(max_length=80)
    grade = models.IntegerField()
    create_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    content = models.CharField(max_length=80)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'password1', 'password2')

reviews/forms.py
from dataclasses import fields
from django import forms
from .models import Review, Comment

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['title', 'content', 'movie_name', 'grade', ]

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content',]

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm
from .forms import CustomUserCreationForm

# Create your views here.

def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('reviews:index')
    else:
        form = CustomUserCreationForm()

    context = {
        'form' : form
    }

    return render(request, 'accounts/signup.html', context)

def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'reviews:index')

    else:
         form = AuthenticationForm()

    context = {
        'form' : form
    }

    return render(request, 'accounts/login.html', context)

def logout(request):
    auth_logout(request)
    return redirect('reviews:index')

reviews/views.py
from django.shortcuts import render, redirect
from .forms import ReviewForm, CommentForm
from .models import Review, Comment
from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):
    reviews = Review.objects.order_by('-pk')

    context = {
        'reviews': reviews
    }
    return render(request, 'reviews/index.html', context)


def create(request):
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.user = request.user
            review.save()
            return redirect('reviews:index')
    else:
        form = ReviewForm()
    
    context = {
        'form' : form
    }

    return render(request, 'reviews/create.html', context)


def detail(request, pk):
    review = Review.objects.get(pk=pk)
    comment_form = CommentForm()

    context = {
        'review' : review,
        'comments' : review.comment_set.all(),
        'comment_form' : comment_form,
    }

    return render(request, 'reviews/detail.html', context)

@login_required
def update(request, pk):
    review = Review.objects.get(pk=pk)
    if request.user == review.user:
        if request.method == 'POST':
            form = ReviewForm(request.POST, instance=review)
            if form.is_valid():
                form.save()
                return redirect('reviews:detail', review.pk)
        else: 
            form = ReviewForm(instance=review)
        
        context = {
            'form' : form
        }

        return render(request, 'reviews/update.html', context)
    
    else:
        return redirect('reviews:detail', review.pk)

def delete(request, pk):
    review = Review.objects.get(pk=pk)
    if request.user == review.user:
        review.delete()
        return redirect('reivews:index')
    else:
        return redirect('reviews:detail', review.pk)

@login_required
def comments(request, pk):
    review = Review.objects.get(pk=pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.review = review
        comment.user = request.user
        comment.save()
    return redirect('reviews:detail', review.pk)


def comments_del(request, review_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    comment.delete()
    return redirect('reviews:detail', review_pk)

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
  <div class="text-center my-5 py-5">
    <h1>로그인</h1>
  </div>

  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <div class="text-end">
      <button class="btn btn-primary" type="submit">로그인</button>
      <a href="{% url 'accounts:signup' %}" class="btn btn-primary">회원 가입</a>
    </div>
  </form>
{% endblock body %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
  <div class="text-center my-5 py-5">
    <h1>회원 가입</h1>
  </div>

  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button class="btn btn-primary float-end" type="submit">가입</button>
  </form>
{% endblock body %}

reviews/templates/reviews/create.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
  <div class="text-center my-5 py-5">
    <h1>글 작성</h1>
  </div>

  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button class="btn btn-primary float-end" type="submit">작성</button>
  </form>
{% endblock body %}

reviews/templates/reviews/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
  <div class="text-center my-5 py-5">
    <h1>{{ review.title }}</h1>
  </div>
  <div class="card">
    <div class="card-body">
      <h2 class="py-3">{{ review.movie_name }}</h2>
      <p>{{ review.content }}</p>
      <p class="float-end">평점 :
        {{ review.grade }}</p>
    </div>
  </div>

  {% if request.user == review.user %}
    <div class="my-3 text-end">
      <a href="{% url 'reviews:update' review.pk %}" class="btn btn-primary">수정</a>
      <a href="{% url 'reviews:delete' review.pk %}" class="btn btn-danger">삭제</a>
    </div>
  {% endif %}
  <div class="my-3">
    <h3 class='py-3'>댓글</h3>
  </div>
  {% for comment in comments %}
    <p>{{ comment.content }}</p>
    <hr>
    <div class='text-end'>
      <span class="font-monospace">{{ comment.user }}</span>
      {% if user == comment.user %}
        <a href="{% url 'reviews:comments_del' review.pk comment.pk %}" class="btn btn-danger btn-sm">삭제</a>
      {% endif %}
    </div>
    {% empty %}
    <p>댓글이 없습니다</p>
  {% endfor %}

  {% if request.user.is_authenticated %}
    <form action="{% url 'reviews:comments' review.pk %}" method="POST">
      {% csrf_token %}
      {% bootstrap_form comment_form %}
      <button class="btn btn-primary" type="submit">작성</button>
    </form>
  {% endif %}

{% endblock body %}

reviews/templates/reviews/index.html
{% extends 'base.html' %}

{% block body %}
  <div class="text-center my-5 py-5">
    <h1>글 목록</h1>
    <div class="text-end my-3">
      {% if request.user.is_authenticated %}
        <a href="{% url 'accounts:logout' %}" class="btn btn-danger">로그아웃</a>
        <a href="{% url 'reviews:create' %}" class="btn btn-primary">글 작성</a>
      {% else %}
        <a href="{% url 'accounts:login' %}" class="btn btn-primary">로그인</a>
      {% endif %}
    </div>
  </div>

  <table class="table">
    <thead>
      <tr>
        <th scope="col">글 제목</th>
        <th scope="col">영화</th>
        <th scope="col">평점</th>
      </tr>
    </thead>
    <tbody>
      {% for review in reviews %}
        <tr>
          <th>
            <a href="{% url 'reviews:detail' review.pk %}">{{ review.title }}</a>
          </th>
          <td>{{ review.movie_name }}</td>
          <td>{{ review.grade }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock body %}

reviews/templates/reviews/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
  <div class="text-center my-5 py-5">
    <h1>글 수정</h1>
  </div>

  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button class="btn btn-primary float-end" type="submit">수정</button>
  </form>
{% endblock body %}

templates/base.html
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  </head>

  <body>
    <div class="container position-relative">
      <a href="{% url 'reviews:index' %}" class="position-absolute top-0 end-0 btn btn-outline-secondary">메인 페이지로</a>
      {% block body %}{% endblock %}
    </div>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>

</html>